config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "home#show"

  resource :home, only: [:show]
  resource :about, only: [:show]
  resource :terms, only: [:show]
  resource :contact, only: [:show, :new, :create]
  resources :projects do
    resources :project_updates
  end
  resources :checkouts, only: :create
  resources :backers, only: :show
  resources :notifications, only: :create
  resources :newsletter, only: :create
  resources :posts
  resources :messages, only: [:new, :create]

  namespace :manager do
    root to: 'dashboard#show'

    resources :dashboard, only: :show
    resources :projects
    resources :users
    resources :rewards
    resources :backers, except: [:create, :new]
    resources :posts
    resources :conversations
  end

  get ':project', to: redirect('/projects/%{project}')
end

app/views/shared/_footer.html.erb
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-4 mbxl text-center">
            <h4>Navegue</h4>
            <ul class="list-unstyled">
              <li><%= link_to "Quem Somos", about_path %></li>
              <li><%= link_to "Contato", contact_path %></li>
              <li><%= link_to "Comece sua campanha", new_project_path %></li>
              <li><%= link_to "Campanhas", projects_path %></li>
            </ul>
          </div>
          <div class="col-lg-4 mbxl text-center">
            <h4>Ajuda</h4>
            <ul class="list-unstyled">
              <li><%= link_to "Termos de Uso", terms_path %></li>
            </ul>
          </div>
          <div class="col-lg-4 text-center">
            <div class="mbl">
              <h4>Newsletter</h4>
              <%= simple_form_for 'newsletter', url: newsletter_index_path, remote: true, html: { class: "form-inline" } do |f| %>
                <div class="input-group newsletter-field mb-4">
                <%= f.input 'email', required: true, label: false, placeholder: 'Digite seu email...', class: 'align-top', input_html: {id: "newsletter-email-input"}%>
                  <div class="input-group-append newsletter-append">
                    <%= f.submit "Enviar", class: "btn btn-secondary newsletter-field-submit form-group" %>
                  </div>
                </div>
              <% end %>
            </div>

            <h4>Nos acompanhe</h4>
            <ul class="list-inline social-footer">
              <li class="list-inline-item"><i class="fab fa-2x fa-twitter"></i></li>
              <li class="list-inline-item"><i class="fab fa-2x fa-facebook-f"></i></li>
              <li class="list-inline-item"><i class="fab fa-2x fa-instagram"></i></li>
            </ul>
          </div>
        </div>
        <hr>
        <div class="row text-center justify-content-center">
          <p class="col-auto">Copyright © 2018 InovaWork</p><br>
          <p class="col-12">Todos os direitos reservados</p>
          <p class="col-auto"><%= image_tag 'moblive.png' %></p>
        </div>
      </div>
    </footer>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110460483-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-110460483-1');
  </script>
  </body>
</html>

app/views/shared/_mobile_navbar.html.erb
<div id="mobile-navbar" class="navbar-overlay">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNavOverlay()">&times;</a>
  <div class="navbar-overlay-content">
    <%= render "shared/navbar_menu" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar paxl navbar-expand-lg navbar-dark">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" onclick="openNavOverlay()" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= render "shared/navbar_menu" %>
    <div class="d-none d-lg-block">
      <%= render "shared/signed_dropdown" %>
    </div>
  </div>

  <%= render "shared/mobile_navbar" %>
</nav>

app/views/shared/_navbar_menu.html.erb
<ul class="navbar-nav ml-auto">
  <% if signed_in? %>
    <li class="nav-item d-block d-lg-none">
      <%= link_to "Minha Conta", edit_user_registration_path, class: "nav-link" %>
    </li>
    <% end %>
  <li class="nav-item">
    <%= link_to "Quem Somos", about_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Campanhas", projects_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Notícias", posts_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Contato", contact_path, class: "nav-link" %>
  </li>
  <% if !signed_in? %>
    <li class="nav-item">
      <%= link_to "Login ou Cadastro", new_user_session_path, class: 'nav-link' %>
    </li>
  <% end %>
  <li class="nav-item">
    <%= form_for Project.new, url: projects_path, method: :get, html: { class: "my-lg-0 my-2" } do |f| %>

      <%= f.button :button, class: 'dnone' %>
      <%= link_to "Crie sua campanha", new_project_path, class: "btn btn-negative" %>
    <% end %>
  </li>
</ul>

app/views/shared/_signed_dropdown.html.erb
<% if signed_in? %>
  <div class="dropdown show">
    <a class="dropdown-toggle" href='#' role="button" id="dropdown_menu" data-toggle="dropdown" aria-haspopup='true' aria-expanded='false' >
      <% unless current_user.avatar_url.blank? %>
        <%= image_tag current_user.avatar_url, width:100, height:100, class: 'navbar-avatar img-fluid project--user' %>
      <% else %>
        <%= image_tag current_user.image_url, class: 'navbar-avatar img-fluid project--user' %>
      <% end %>
    </a>
    <div class="dropdown-menu dropdown-menu-right dropdown-custom-style" aria-labelledby="dropdown_menu">
      <%= link_to "Minha Conta", edit_user_registration_path, class: "nav-link dropdown-item" %>
      <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "nav-link dropdown-item" %>
    </div>
  </div>
<% end %>