config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "home#show"

  resource :home, only: [:show]
  resource :about, only: [:show]
  resource :terms, only: [:show]
  resource :contact, only: [:show, :new, :create]
  resources :projects do
    resources :project_updates
  end
  resources :checkouts, only: :create
  resources :backers, only: :show
  resources :notifications, only: :create
  resources :newsletter, only: :create
  resources :posts
  resources :messages, only: [:new, :create]

  namespace :manager do
    root to: 'dashboard#show'

    resources :dashboard, only: :show
    resources :projects
    resources :users
    resources :rewards
    resources :backers, except: [:create, :new]
    resources :posts
    resources :conversations
  end

  get ':project', to: redirect('/projects/%{project}')
end

app/models/project.rb
class Project < ApplicationRecord
  include AASM
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  belongs_to :bank_account, optional: true
  belongs_to :project_category

  has_one :project_total
  has_many :backers
  has_many :updates, class_name: 'ProjectUpdate'
  has_many :rewards
  has_many :conversations
  has_many :messages, through: :conversations

  accepts_nested_attributes_for :rewards, reject_if: :all_blank, allow_destroy: true

  scope :with_project_totals, -> { joins('LEFT OUTER JOIN project_totals ON project_totals.project_id = projects.id') }
  scope :order_highlight, -> { where(highlight: true).order(id: :desc) }
  scope :only_active, -> { where.not(status: [:draft, :awaiting_approval, :rejected]).where(visible: true).order(id: :desc) }
  scope :only_drafts, -> { where(status: [:draft, :awaiting_approval, :rejected]) }

  default_scope { order("created_at DESC") }

  aasm column: :status do
    state :draft, initial: true
    state :awaiting_approval
    state :rejected
    state :approved
    state :in_progress
    state :successful
    state :failed

    event :send_to_approve do
      transitions from: [:draft, :rejected], to: :awaiting_approval
    end

    event :approve do
      transitions from: [:draft, :rejected, :awaiting_approval], to: :approved
    end

    event :reject do
      transitions from: [:draft, :approved, :awaiting_approval], to: :rejected
    end

    event :publish do
      transitions from: [:draft, :approved, :awaiting_approval], to: :in_progress
    end

    event :success do
      transitions from: :in_progress, to: :successful
    end

    event :fail do
      transitions from: :in_progress, to: :failed
    end
  end


  def summary
    text = self.headline.blank? ? self.about : self.headline
    text.truncate(115, separator: /\s/)
  end

  def total
    self.backers.only_paid.sum(:value)
  end

  def progress
    progress = goal.blank? || goal.zero? ? 100 : (total / goal * 100)
    progress.to_f.round(2)
  end
end

app/controllers/manager/projects_controller.rb
class Manager::ProjectsController < Manager::BaseController
  private

  def object
    @project ||= params[:id].present? ? Project.friendly.find(params[:id]) : Project.new(object_params)
  end

  def collection
    @projects ||= Project.all
  end

  def object_params
    params.fetch(:project, {}).permit(:id, :name, :user_id, :project_category_id, :goal, :expires_at, :about,
      :headline, :video_url, :image_url, :slug, :status, :visible,
      rewards_attributes: [:id, :minimum_value, :maximum_backers, :observation_description, :delivery_date, :description, :image_url, :_destroy])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :project_categories, only: [:new, :edit]
  before_action :backers, only: [:show, :new, :edit]
  before_action :drafts, only: [:index]
  before_action :bank_account, only: [:create, :update]
  before_action :set_status, only: [:create, :update]
  before_action :message, only: [:show]
  after_action :read_messages, only: [:show]

  def index
    respond_with collection
  end

  def show
    respond_with object
  end

  def new
    respond_with object
  end

  def edit
    respond_with object
  end

  def create
    if object.valid?
      object.save
      flash[:notice] = 'Campanha criada com sucesso!'
      redirect_to @project
    else
      flash[:notice] = 'Erro ao salvar campanha. Tente novamente!'
      redirect_back fallback_location: root_path
    end
  end

  def update
    if object.valid?
      object.update(project_params)
      flash[:notice] = 'Campanha atualizada com sucesso!'
      redirect_to controller: params[:controller], action: :index
    else
      flash[:notice] = 'Erro ao salvar campanha. Tente novamente!'
      redirect_back fallback_location: root_path
    end
  end

  private

  def set_status
    return unless params[:status].present?

    case params[:status]
    when "send_to_approve"
      object.send_to_approve!
    when "publish"
      object.publish!
    end
  end

  def message
    @conversation = set_convesation
    @message = @conversation.messages.new
  end

  def stored_conversation
    Conversation.where(project: object, sender: current_user).take
  end

  def set_convesation
    stored_conversation.present? ?
      stored_conversation :
      object.conversations.create({ sender: current_user })
  end

  def read_messages
    object.messages.only_unread(current_user).update(is_read: true)
  end

  def default_recipient
    user_id = ENV["DEFAULT_USER_ID_TO_CONVERSATION"]
    User.find(user_id)
  end

  def project_categories
    @project_categories = ProjectCategory.all
  end

  def collection
    @q = Project.only_active.order_highlight.ransack(params[:q])
    @projects = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 40)
  end

  def drafts
    @project_drafts = current_user.projects.only_drafts if current_user.present?
  end

  def object
    @project ||= params[:id].present? ? Project.friendly.find(params[:id]) : current_user.projects.new(project_params)
    @project.bank_account = @bank_account if @bank_account.present?
    return @project
  end

  def backers
    if object.present?
      @backers = (can? :manage, @project) ? @project.backers : @project.backers.only_paid
    end
  end

  def bank_account
    @bank_account = BankAccount.new(project_params[:bank_account]) if project_params[:bank_account].present?
    @bank_account.user = current_user
    @bank_account.save! if @bank_account.valid?
    params[:project].delete(:bank_account) if @bank_account.present?
  end

  def project_params
    params.fetch(:project, {}).permit(:name, :goal, :expires_at, :about, :headline, :video_url,
      :image_url, :budget_image_url, :status, :project_category_id, :slug, rewards_attributes: [:id, :delivery_date, :minimum_value,
      :maximum_backers, :observation_description, :description, :image_url, :position, :_destroy], bank_account: [:bank_code, :agency, :agency_vd,
        :account, :account_vd, :document_number, :legal_name])
  end
end

app/helpers/project_helper.rb
module ProjectHelper
  def bn_image(project)
    "background-image: linear-gradient(90deg, rgba(0,56,77, 80%), rgba(0,56,77,0) 50%), linear-gradient(180deg, rgba(0,56,77,80%), rgba(0,56,77,0) 50%), url('#{project.image_url}');"
  end

  def format_month_year_date(date, format = '%m/%Y')
    l date.to_date, :format => format
  end

  def show_time_left(project)
    difference = time_left(project)

    if (difference.nil? || difference < 0)
      "Encerrada"
    elsif (difference == 0)
      "Encerra hoje"
    else
      "#{difference} dias restantes"
    end
  end

  def time_left(project)
    project.expires_at.present? ? (project.expires_at - Date.today).to_i : nil
  end

  def reward_can_be_backed?(reward)
    backers_reward_count = Backer.only_not_canceled.where(reward: reward).count
    project_can_be_backed?(reward.project) && reward.maximum_backers.present? && backers_reward_count < reward.maximum_backers
  end

  def project_can_be_backed?(project)
    difference = time_left project
    !difference.nil? && difference >= 0
  end

  def status_label(backer)
    backer.status === "paid" ? "Aprovado" : "Aguardando Compensaçāo"
  end
end

app/views/projects/_box.html.erb
<div class="box box-project">
  <%= link_to project_path(project) do %>
    <% if project.image_url.present? %>
    <div class="project-thumb img-fluid" style='background-image: url(<%= project.image_url %>)'></div>
    <% else %>
      <%= image_tag 'bn.jpg', class: 'box-image-cover' %>
    <% end %>
    <span class="project--progress-percent">
      <%= project.progress.to_i %>%
    </span>
    <div class="box-content box-content-text">
      <h4><%= project.name %></h4>
      <p class="box-project-summary"><%= project.summary %></p>
      <% if has_unread_messages?(project.conversations.last, current_user) %>
        <p>Mensagens Não Lidas <%= unread_conversation_badge(project.conversations.last, current_user) %></p>
      <% end %>
    </div>
    <%= render 'projects/progress', project: project %>
    <div class="box-content">
      <div class="row">
        <div class="col-auto">
          <strong class="text-secondary"><%= amount_to_real project.total %></strong>
        </div>
        <div class="col-auto ml-auto">
          <%= show_time_left project %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/_box_new.html.erb
<div class="col-lg-4 col-sm-12">
  <div class="box box-project box-new">
    <div class="box-content text-center">
      <%= link_to new_project_path do %>
        <i class="fas fa-plus-circle fa-8x mbxl text-muted"></i>
      <% end %>
      <h3 class="ptxl pbxl">Sua campanha aqui</h3>
      <p class="pbxl">A Alster estará sempre do seu lado dando o apoio para que tudo der certo. Assim que a campanha encerrar, você receberá o seu dinheiro, e poderá realizar o seu objetivo.</p>
      <%= link_to "Crie sua campanha", new_project_path, class: "btn btn-secondary btn-block btn-spaced" %>
    </div>
  </div>
</div>

app/views/projects/_box_wrapper.html.erb
<div data-turbolinks="false" class="col-sm-12 col-md-<%= (defined? size) != nil ? size : "4" %>" >
  <%= render 'projects/box', project: project %>
</div>

app/views/projects/_form.html.erb
<% if project.awaiting_approval? %>
  <div class="alert alert-warning text-center mbxl">
    Aguardando Aprovação pela Equipe da Alster!
  </div>
<% end %>

<% if project.rejected? %>
  <div class="alert alert-danger text-center mbxl">
    Ajuste seu projeto de acordo com o solicitado pela Equipe da Alster!
  </div>
<% end %>

<%= simple_form_for project, html: { class: 'form-horizontal' } do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, label: "Nome da Campanha", required: true %>
  <small class="form-text text-muted">Dê um nome que as pessoas se lembrem facilmente. Não ultrapasse 50 caracteres.</small>

  <%= f.input :goal, label: "Meta em R$", placeholder: 'Meta à ser arrecadada', required: true %>

  <%= f.input :expires_at, as: :date, order: [:day, :month, :year], label: "Prazo da campanha", placeholder: '', required: true %>

  <%= f.association :project_category, collection: @project_categories.ordered_by_name, label: "Modalidade da Campanha", placeholder: "- Selecione uma modalidade -" %>
  <small class="form-text text-muted">Escolha a mais adequada à sua campanha.</small>

  <%= f.input :headline, label: "Frase de Cabeçalho" %>

  <div class="input-big">
    <%= f.input :about, label: "Descrição da Campanha", required: true %>
  </div>

  <div class="row pbxl">
    <div class="col-md-12 col-lg-6 upload">
      <label for="">Imagem da Campanha</label>
      <%= f.filestack_field :image_url, 'Enviar imagem', id: "header", pickerOptions: {'fromSources': ['local_file_system', 'googledrive', 'dropbox', 'gmail', 'facebook', 'instagram']}, onchange: 'Projects.onUpload(event)', class: 'btn btn-secondary btn-upload btn-block' %>
    </div>
    <div class="col-md-12 col-lg-6 upload">
      <label for="">Orçamento da Campanha</label>
      <%= f.filestack_field :budget_image_url, 'Enviar imagem', id: "budget", pickerOptions: {'fromSources': ['local_file_system', 'googledrive', 'dropbox', 'gmail', 'facebook', 'instagram']}, onchange: 'Projects.onUpload(event)', class: 'btn btn-secondary btn-upload btn-block' %>
    </div>
  </div>

  <%= f.input :video_url, as: :string, label: "Vídeo do Youtube / Vimeo" %>
  <small class="form-text text-muted">Caso você já tenha produzido um vídeo da campanha, basta colar o link dele.</small>

  <div id="bank_account" class="mbxl">
    <h3> Conta Bancária </h3>
    <%= f.simple_fields_for :bank_account do |b| %>
      <%= b.input :bank_code, label: "Código do Banco" %>
      <%= b.input :agency, label: "Agência" %>
      <%= b.input :agency_vd, label: "Dígito Verificador da Agência", input_html: { class: "col-md-2" } %>
      <%= b.input :account, label: "Conta" %>
      <%= b.input :account_vd, label: "Dígito Verificador da Conta", input_html: { class: "col-md-2" } %>
      <%= b.input :document_number, label: "Número do Documento" %>
      <%= b.input :legal_name, label: "Nome do Titular" %>
    <% end %>
  </div>

  <div id="rewards" class="mbxl fieldset-block">
    <h3 class="text-primary">Recompensas</h3>

    <%= f.simple_fields_for :rewards do |reward| %>
      <%= render "reward_fields", f: reward %>
    <% end %>
    <div class="links">
      <hr>
      <%= link_to_add_association 'Adicionar Recompensa', f, :rewards, class: 'btn btn-success'  %>
    </div>
  </div>

  <div>
    <%= f.button :button, "Salvar", class: "btn btn-primary" %>
    <%= f.button :button, "Enviar para Aprovação", name: "status", value: "send_to_approve", class: "btn btn-success" if (project.draft? or project.rejected?) %>
    <%= f.button :button, "Publicar", name: "status", value: "publish", class: "btn btn-success" if project.approved? %>
  </div>
<% end %>

app/views/projects/_progress.html.erb
<div class="progress">
  <div class="progress-bar bg-info" role="progressbar" style="width: <%= project.progress %>%" aria-valuenow="<%= project.progress %>" aria-valuemin="0" aria-valuemax="100"></div>
</div>

app/views/projects/_reward_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-md-4">
      <%= f.input :position, type: :number, label: "Ordenação" %>
    </div>
    <div class="col-md-4 currency">
      <%= f.input :minimum_value, label: "Valor mínimo", as: :string %>
    </div>
    <div class="col-md-4">
      <%= f.input :maximum_backers, label: "Máximo de contribuições" %>
    </div>
    <div class="col-12">
      <%= f.input :delivery_date, label: "Data Estimada de Entrega" %>
    </div>
  </div>
  <%= f.input :observation_description, label: "Observações", placeholder: "Tamanho e cores disponíveis, endereço de entrega, etc ... " %>
  <%= f.input :description, label: "Descrição" %>
  <%= f.filestack_field :image_url, 'Enviar imagem', input_id: "#{f.object_id}", pickerOptions: {'fromSources': ['local_file_system', 'googledrive', 'dropbox', 'gmail', 'facebook', 'instagram']}, onchange: 'Projects.Rewards.onUpload(event)',class: 'btn btn-secondary btn-upload btn-block mbl' %>

  <%= link_to_remove_association "Remover Recompensa", f, class: 'btn btn-danger'  %>
</div>

app/views/projects/edit.html.erb
<% content_for :bn, 'bn-projects' %>
<% content_for :bnimage, bn_image(@project) if @project.image_url.present? %>

<% content_for :head do %>
  <div class="container">
    <h2 class="title project-title text-negative">Gerencie sua campanha</h2>
  </div>
<% end %>

<div class="bg-light content">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <%= render "form", project: @project %>
      </div>
      <div class="col-md-4 mtxl">
        <div class="phl">
          <h4>1. Comece sua campanha</h4>
          <p>É importante começar... Um ótimo primeiro passo para transformar sua ideia em uma campanha de financiamento coletivo é escrever um rascunho na Alster. Estaremos aqui pra ajudar.</p>

          <h4 class="ptl">2. Estude e planeje</h4>
          <p>Produza a sua campanha com carinho e no tempo certo. Planejar uma boa campanha é fator decisivo para o sucesso do seu financiamento coletivo. Disponibilizamos uma série de materiais para te auxiliar!</p>

          <h4 class="ptl">3. Mobilize apoiadores</h4>
          <p>Comunique-se bem durante sua campanha e trate bem seus apoiadores! Eles são a força da sua campanha e são quem realmente vai determinar o sucesso ou não da campanha! A Alster é o caminho de você se aproximar das pessoas que gostam do seu trabalho, expandir essa rede e formar público.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<% content_for :bn, 'bn-projects' %>

<% content_for :head do %>
<% end %>

<div class="bg-light content">
  <div class="container">
    <% if @project_drafts.present? %>
      <h2 class="text-primary pbxl">Campanhas em Rascunho</h2>

      <% @project_drafts.each_slice(3) do |drafts| %>
        <div class="row">
          <% drafts.each do |draft| %>
            <%= render 'projects/box_wrapper', project: draft %>
          <% end %>
        </div>
      <% end %>
    <% end %>

    <h2 class="text-primary pbxl">Campanhas</h2>

    <% @projects.each_slice(3) do |projects| %>
      <div class="row">
        <% projects.each do |project| %>
          <%= render 'projects/box_wrapper', project: project %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<% content_for :bn, 'bn-projects' %>

<% content_for :head do %>
  <div class="container">
    <h2 class="title project-title text-negative">Crie sua campanha</h2>
  </div>
<% end %>

<div class="bg-light content">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="phl">
          <h4>1. Comece sua campanha</h4>
          <p>É importante começar... Um ótimo primeiro passo para transformar sua ideia em uma campanha de financiamento coletivo é escrever um rascunho na Alster. Estaremos aqui pra ajudar.</p>

          <h4 class="ptl">2. Estude e planeje</h4>
          <p>Produza a sua campanha com carinho e no tempo certo. Planejar uma boa campanha é fator decisivo para o sucesso do seu financiamento coletivo. Disponibilizamos uma série de materiais para te auxiliar!</p>

          <h4 class="ptl">3. Mobilize apoiadores</h4>
          <p>Comunique-se bem durante sua campanha e trate bem seus apoiadores! Eles são a força da sua campanha e são quem realmente vai determinar o sucesso ou não da campanha! A Alster é o caminho de você se aproximar das pessoas que gostam do seu trabalho, expandir essa rede e formar público.</p>
        </div>
      </div>
      <div class="col-md-8">
        <%= render "form", project: @project %>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% content_for :bn, 'bn-projects' %>
<% content_for :bnimage, bn_image(@project) if @project.image_url.present? %>

<% content_for :head do %>
  <div class="container">
    <h2 class="title project-title text-negative"><%= @project.name %></h2>
  </div>
<% end %>

<% if flash[:error].present? %>
  <script type="text/javascript">
    toastr.error("<%= flash[:error] %>")
  </script>
<% end %>

<div class="bg-light content">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-7 order-md-first order-last">
        <ul class="nav nav-pills nav-fill pbxl" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="pill" href="#project">Sobre a campanha</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="pill" href="#updates">Notícias (<%= @project.updates.size %>)</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="pill" href="#backers">Apoios (<%= @backers.present? ? @backers.size : 0 %>)</a>
          </li>
          <% if can? :manage, @project %>
            <li class="nav-item">
              <%= link_to 'Editar campanha', edit_project_path(@project), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="pill" href="#conversations">Mensagens <%= unread_conversation_badge(@conversation, current_user) %></a>
            </li>
          <% end %>
        </ul>

        <div class="tab-content" id="myTabContent">

          <!-- Project Details START -->
          <div class="tab-pane fade show active" id="project">
            <% if @project.video_url.present? %>
              <div class="project--embed">
                <%= get_video_iframe(@project.video_url, '100%', '500px') %>
              </div>
            <% end %>
            <h3><%= @project.headline %></h3>
            <p><%= auto_link (simple_format @project.about, :html => { :target => '_blank' }) %></p>
            <% if @project.budget_image_url.present? %>
              <p><%= image_tag @project.budget_image_url, width:850, height:400, class: 'img-fluid' %></p>
            <% end %>
          </div>
          <!-- Project Details END -->

          <!-- Project News START -->
          <div class="tab-pane fade show" id="updates">
            <h3 class="pbxl">Notícias</h3>
            <div class="project-updates">
              <% if @project.updates.present? %>
                <% @project.updates.each do |project_update| %>
                  <%= render "project_updates/card", project_update: project_update %>
                <% end %>
              <% else %>
                <div class="alert alert-primary">
                  Nenhuma notícia para esta campanha
                </div>
              <% end %>
            </div>
            <% if can? :manage, @project %>
              <div class="fieldset-block">
                <%= render "project_updates/form", project: @project %>
              </div>
            <% end %>
          </div>
          <!-- Project News END -->

          <!-- Project Backers START -->
          <div class="tab-pane backer-list fade show" id="backers">
            <h3 class="pbxl">Apoios</h3>
            <% if @backers.present? %>
              <% @backers.each do |backer| %>
                <div class="row backer-list-item">
                  <div class="col-md-2">
                    <%= image_tag (backer.anonymous? ? 'no-image.png' : backer.user.image_url), class: 'img-fluid project--user' %>
                  </div>
                  <div class="col-md-10">
                    <h4><%= backer.anonymous? ? "Anônimo" : backer.user.try(:name) %></h4>
                    <% if can? :manage, @project %>
                      <p><%= amount_to_real backer.try(:value) %>
                      <small class="status_label">(<%= status_label backer %>)</small>
                    <% end %>
                    <br /><%= time_ago_in_words backer.created_at %> atrás</p>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div class="alert alert-primary">
                Nenhuma apoio realizado para esta campanha
              </div>
            <% end %>
          </div>
          <!-- Project Backers END -->

          <!-- Project Messages START -->
          <div class="tab-pane fade show" id="conversations">
            <h3 class="pbxl">Mensagens</h3>
            <%= render "messages/show", conversation: @conversation %>
          </div>
          <!-- Project Messages END -->
        </div>

      </div>
      <div class="col-lg-4 col-md-5 order-md-last order-first">
        <div class="sidebar">
          <div class="sidebar--user">
            <%= image_tag @project.user.image_url, class: 'sidebar--user__image img-fluid' %>
            <h4 class="sidebar--user__name"><%= @project.user.try(:name) %></h4>
            <% if @project.user.bio.present? %>
              <p><%= @project.user.bio %></p>
            <% end %>
          </div>

          <div>
            <div class="row">
              <div class="col-6">
                <h4 class="sidebar--content text-secondary"><%= @project.progress %>%</h4>
              </div>
              <div class="col-6 sidebar--content__amount">
                <h4 class="sidebar--content"><%= amount_to_real @project.goal %></h4>
              </div>
            </div>
            <%= render "projects/progress", project: @project %>
            <div class="sidebar--content">
              <div class="row">
                <div class="col-auto">
                  <strong class="text-secondary"><%= amount_to_real @project.total %></strong>
                </div>
                <div class="col-auto ml-auto">
                  <%= show_time_left @project %>
                </div>
                <div class="col-12 social-share-div">
                  <%= social_share_button_tag('Share to Facebook', desc: @project.name, :allow_sites => %w(facebook)) %>
                </div>
              </div>
            </div>
            <h5 class="ptl text-center">Quer apoiar esta campanha?</h5>

          <% if project_can_be_backed?(@project)%>
              <div class="sidebar--box reward_nil">
                <h3>Escolha o valor</h3>
                <p>Não quero recompensa, apenas apoiar esta campanha</p>
                <%= render 'checkouts/form', project: @project, reward: nil, id: nil %>
              </div>
            <% end %>

            <% if @project.rewards.present? %>
              <% @project.rewards.order_by_position.each do |reward| %>
                <div class="sidebar--box <%= dom_id(reward) %>">
                  <%= image_tag reward.image_url, class: 'img-fluid pbxl' if reward.image_url.present? %>
                  <h3><%= amount_to_real reward.minimum_value %> ou mais</h3>
                  <p><%= reward.description %></p>
                  <% if reward.delivery_date.present? %>
                    <h6>Entrega Estimada:</h6><p><%= format_month_year_date reward.delivery_date %></p>
                  <% end %>
                  <%= render 'checkouts/form', id: dom_id(reward), reward: reward if reward_can_be_backed?(reward) %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>