config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "home#show"

  resource :home, only: [:show]
  resource :about, only: [:show]
  resource :terms, only: [:show]
  resource :contact, only: [:show, :new, :create]
  resources :projects do
    resources :project_updates
  end
  resources :checkouts, only: :create
  resources :backers, only: :show
  resources :notifications, only: :create
  resources :newsletter, only: :create
  resources :posts
  resources :messages, only: [:new, :create]

  namespace :manager do
    root to: 'dashboard#show'

    resources :dashboard, only: :show
    resources :projects
    resources :users
    resources :rewards
    resources :backers, except: [:create, :new]
    resources :posts
    resources :conversations
  end

  get ':project', to: redirect('/projects/%{project}')
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create
  before_action :project, only: :create

  def create
    if @project.present? && @project.visible && @project.expires_at >= Date.new && params[:payment_service].present?
      backer = BackerService.new(current_user, params).process
      return redirect_to backer_path(backer) if backer.present?
      flash[:error] = "Ocorreu um erro ao tentar completar a transação. Tente novamente mais tarde"
      redirect_back fallback_location: request.referrer
    end
  end

  private

  def project
    @project = Project.find(params[:project_id])
  end
end

app/views/checkouts/_form.html.erb
<%= simple_form_for :checkout, url: checkouts_path(project_id: (reward.present? ? reward.project.id : project.id), reward_id: (reward.present? ? reward.id : nil)), method: :post, :html => { class: 'checkout-form',
    :'data-logged' => signed_in?,
    :'data-min-value' => (reward.present? ? reward.minimum_value : 0),
    :'data-customer-email' => (current_user.email if current_user.present?),
    :'data-customer-name' => (current_user.name if current_user.present?),
    :'data-customer-document-number'=> (current_user.document if current_user.present? and current_user.document.present?),
    :'data-customer-phone-ddd'=> (current_user.phone_area_code if current_user.present? and current_user.phone_area_code.present?),
    :'data-customer-phone-number' => (current_user.phone if current_user.present? and current_user.phone.present?),
    :'data-customer-address-neighborhood'=> (current_user.address.neighborhood if current_user.present? and current_user.address.present?),
    :'data-customer-address-street'=> (current_user.address.address if current_user.present? and current_user.address.present?),
    :'data-customer-address-street-number'=> (current_user.address.number if current_user.present? and current_user.address.present?),
    :'data-customer-address-complementary'=> (current_user.address.complement if current_user.present? and current_user.address.present?),
    :'data-customer-address-zipcode'=> (current_user.address.zipcode if current_user.present? and current_user.address.present?)} do |f| %>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">R$</span>
    </div>
    <%= f.input :amount, label: false, wrapper: false, input_html: {
      class: 'amount_to_real',
      placeholder: (reward.present? and reward.minimum_value > 0) ? amount_to_float(reward.minimum_value) : "Digite o valor",
      value: (amount_to_float(reward.minimum_value) if (reward.present? and reward.minimum_value > 0))
    } %>
  </div>
  <% if reward.present? %>
    <% if reward.observation_description.present? %>
      <label> Observações </label>
      <%= f.input :observation, placeholder: reward.observation_description , label: false, as: :text, required: false %>
    <% end %>
    <div class="input-group">
      <%= f.input :anonymous, as: :boolean, label: "Doação anônima" %>
    </div>
    <div class="input-group mb-3">
      <%= f.input :refund_if_not_success, as: :boolean, label: "Quero que o valor seja estornado, caso a campanha não atinja 100%" %>
    </div>
  <% end %>
  <%= render "checkouts/payment_services", f: f, id: id %>
<% end %>

app/views/checkouts/_payment_services.html.erb
<button type="button" class="btn payment-service-toggle btn-block btn-primary" data-toggle="modal">
  Apoiar
</button>

<div class="modal fade" id="payment-service-modal" tabindex="-1" role="dialog" aria-labelledby="payment-service-modal-label" aria-hidden="true" data-id=<%= id.present? ? id : "reward_nil" %>>
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="payment-service-modal-label">Escolha um método de Pagamento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
        <%= f.button :button, class: 'btn btn-primary btn-block mvl', data: {"payment-service-button": true} do %>
          Apoiar com Pagar.me
        <% end %>
        <div id="paypal-button-container" data-payment-service-button class="mvl"></div>
      </div>
    </div>
  </div>
</div>