config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "home#show"

  resource :home, only: [:show]
  resource :about, only: [:show]
  resource :terms, only: [:show]
  resource :contact, only: [:show, :new, :create]
  resources :projects do
    resources :project_updates
  end
  resources :checkouts, only: :create
  resources :backers, only: :show
  resources :notifications, only: :create
  resources :newsletter, only: :create
  resources :posts
  resources :messages, only: [:new, :create]

  namespace :manager do
    root to: 'dashboard#show'

    resources :dashboard, only: :show
    resources :projects
    resources :users
    resources :rewards
    resources :backers, except: [:create, :new]
    resources :posts
    resources :conversations
  end

  get ':project', to: redirect('/projects/%{project}')
end

app/models/backer.rb
class Backer < ApplicationRecord
  PAID_STATES = [:processing, :authorized, :paid, :refunded, :waiting_payment, :pending_refund, :refused]

  belongs_to :project
  belongs_to :reward, optional: true
  belongs_to :user

  scope :only_paid, -> { where(status: :paid) }
  scope :only_not_canceled, -> { where(status: [:paid, :authorized, :processing, :waiting_payment]) }
end

app/controllers/backers_controller.rb
class BackersController < ApplicationController
  before_action :authenticate_user!

  load_and_authorize_resource

  def show
    respond_with backer
  end

  private

  def backer
    @backer = params[:id].present? ? current_user.backers.find(params[:id]) : Backer.new(backer_params)
  end

  def backers
    @backers = current_user.backers if current_user.present?
  end

  def backer_params
    params.fetch(:backer, {}).permit(:user_id, :project_id, :observation, :reward_id, :value, :status, :payment_method, :payment_id)
  end
end

app/controllers/manager/backers_controller.rb
class Manager::BackersController < Manager::BaseController
  private

  def object
    @backer ||= params[:id].present? ? Backer.find(params[:id]) : Backer.new(object_params)
  end

  def collection
    @q ||= Backer.ransack(params[:q])
    @backers ||= @q.result(distinct: true)
  end

  def object_params
    params.fetch(:backer, {}).permit(:id, :user_id, :project_id, :value, :reward_id, :status, :created_at)
  end
end

app/controllers/manager/base_controller.rb
class Manager::BaseController < ApplicationController
  layout "manager"

  before_action :check_permission

  respond_to :html, :js

  add_breadcrumb "Dashboard", controller: "dashboard", action: :show

  def index
    add_breadcrumb "#{t("controller_name.#{params[:controller]}")}", action: :index

    respond_with(:manager, collection)
  end

  def show
    add_breadcrumb "#{t("controller_name.#{params[:controller]}")}", action: :index
    add_breadcrumb "Visualização", action: :show

    respond_with(:manager, object)
  end

  def new
    respond_with(:manager, object)
  end

  def edit
    add_breadcrumb "#{t("controller_name.#{params[:controller]}")}", action: :index
    add_breadcrumb "Editar #{t("controller_name.#{params[:controller]}").singularize}", action: :new

    respond_with(:manager, object)
  end

  def create
    if object.valid?
      object.save
      flash[:notice] = 'Criado com sucesso!'
      redirect_to controller: params[:controller], action: :index
    else
      flash[:notice] = 'Erro ao salvar. Tente novamente!'
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    object.update(object_params)
    flash[:notice] = 'Atualizado com sucesso!'
    redirect_to controller: params[:controller], action: :index
  end

  def destroy
    object.destroy if can? :destroy, object
    respond_with(:manager, object)
  end

  def check_permission
    redirect_to root_path if cannot? :manage, :all
  end
end

app/controllers/manager/conversations_controller.rb
class Manager::ConversationsController < Manager::BaseController
  respond_to :html

  def show
    add_breadcrumb t("controller_name.manager/conversations"), manager_conversations_path
    add_breadcrumb object.sender.name, manager_conversations_path(object)
    object.messages.only_unread(current_user).update(is_read: true)

    respond_with object
  end

  private

  def object
    @conversation = params[:id].present? ? Conversation.find(params[:id]) : Conversation.new(object_params)
  end

  def collection
    @conversations = Conversation.all
  end

  def object_params
    params.fetch(:message, {}).permit(:recipient_id, :project_id).merge(sender_id: current_user.id)
  end
end

app/controllers/manager/dashboard_controller.rb
class Manager::DashboardController < Manager::BaseController
  def show
  end
end

app/controllers/manager/projects_controller.rb
class Manager::ProjectsController < Manager::BaseController
  private

  def object
    @project ||= params[:id].present? ? Project.friendly.find(params[:id]) : Project.new(object_params)
  end

  def collection
    @projects ||= Project.all
  end

  def object_params
    params.fetch(:project, {}).permit(:id, :name, :user_id, :project_category_id, :goal, :expires_at, :about,
      :headline, :video_url, :image_url, :slug, :status, :visible,
      rewards_attributes: [:id, :minimum_value, :maximum_backers, :observation_description, :delivery_date, :description, :image_url, :_destroy])
  end
end

app/controllers/manager/rewards_controller.rb
class Manager::RewardsController < Manager::BaseController
  private

  def object
    @reward ||= params[:id].present? ? Reward.find(params[:id]) : Reward.new(object_params)
  end

  def collection
    @rewards ||= Reward.all
  end

  def object_params
    params.fetch(:reward, {}).permit(:id, :minimum_value, :project, :maximum_backers, :image_url, :created_at, :updated_at)
  end
end

app/controllers/manager/users_controller.rb
class Manager::UsersController < Manager::BaseController
  private

  def object
    @user ||= params[:id].present? ? User.find(params[:id]) : User.new(object_params)
  end

  def collection
    @users ||= User.all
  end

  def object_params
    params.fetch(:user, {}).permit(:id, :name, :email, :password, :password_confirmation)
  end
end

app/helpers/manager/backers_helper.rb
module Manager::BackersHelper
end

app/helpers/manager/manager_helper.rb
module Manager::ManagerHelper
  def is_active_controller?(controller_name)
    params[:controller] == controller_name ? "active" : nil
  end

  def is_controller?(controller_name)
    params[:controller] == controller_name
  end

  def is_active_action?(action_name)
    params[:action] == action_name ? "active" : nil
  end

  def is_action?(action_name)
    params[:action] === action_name
  end

  def format_date(date)
    l date.to_date, :format => :default if date.present?
  end

  def format_hour(hour)
    l hour.to_time, :format => :default
  end

  def amount_to_real(amount)
    number_to_currency(amount, unit: "R$ ", separator: ",", delimiter: "")
  end

  def amount_to_price(amount)
    number_with_precision(amount, precision: 2, separator: ",", delimiter: "")
  end

  def percentage_to_number(value)
    number_with_precision(value, precision: 2, separator: ',')
  end

  def path_new_exists?(controller)
    controller_name = controller.gsub('/', '_')
    begin
      Rails.application.routes.recognize_path(send("new_#{(controller_name).singularize}_path"))
    rescue => exception
      return false
    end

    return true
  end

  def path_to_new(controller)
    controller_name = controller.gsub('/', '_')
    send("new_#{(controller_name).singularize}_path")
  end
end

app/helpers/manager/rewards_helper.rb
module Manager::RewardsHelper
end

app/views/manager/backers/_form.html.erb
<%= simple_form_for [:manager, @backer], wrapper: :vertical_form do |f| %>
  <%= f.error_notification %>
  <% if @backer.id.blank? %>
    <div class="row ">
      <div class="col-md-6">
        <%= f.input :user, label: "Usuario" %>
      </div>
      <div class="col-md-6">
        <%= f.input :project, label: "Projeto" %>
      </div>
      <div class="col-md-6">
        <%= f.input :value, label: "Valor" %>
      </div>
      <div class="col-md-6">
        <%= f.input :reward, label: "Recompensa" %>
      </div>
    </div>
  <% end %>
  <div class="row justify-content-md-center">
    <div class="col-md-4">
      <%= f.input :status, as: :select, collection: Backer::PAID_STATES, label: "Status" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= f.button :button, class: 'btn btn-success btn-lg pull-right' do %>
        <span class="fa fa-save"></span> Salvar
      <% end %>
    </div>
  </div>
<% end %>

app/views/manager/backers/_list.html.erb
<table class="table table-striped table-borderless">
  <thead>
    <tr>
      <th>Projeto</th>
      <th>Usuário</th>
      <th>Recompensa</th>
      <th>Valor</th>
      <th>Status</th>
      <th class="actions" style="width:5%;"></th>
    </tr>
  </thead>
  <tbody class="no-border-x">
    <% @backers.each do |backer| %>
      <tr>
        <td><%= link_to backer.project.name, edit_manager_project_path(backer.project), class: 'icon' %></td>
        <td><%= link_to backer.user.name, edit_manager_user_path(backer.user), class: 'icon' %></td>
        <td><%= backer.reward_id %></td>
        <td><%= amount_to_real backer.value %></td>
        <td><%= backer.status %></td>
        <td class="actions">
          <%= link_to raw("<i class='mdi mdi-plus-circle-o'></i>"),
          edit_manager_backer_path(backer), class: "icon" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/manager/backers/_search.html.erb
<%= simple_form_for @q, url: manager_backers_path, method: :get, wrapper: :vertical_form do |f| %>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :project_name_cont, label: "Projeto" %>
    </div>
    <div class="col-md-4">
      <%= f.input :status_eq, as: :select, collection: Backer::PAID_STATES , label: "Status", placeholder: " - Selecione um Status - " %>
    </div>
  </div>
  <div class="toolbar row">
    <div class="actions col-md-4 tet-right ptxl">
      <%= link_to manager_backers_path, class: 'btn btn-secondary' do %>
        <span class="fa fa-close"></span> Limpar Filtros
      <% end %>
      <%= f.button :submit, "Filtrar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/manager/backers/edit.html.erb
<div class="card card-border-color card-border-color-primary">
  <div class="card-body mtl">
    <%= render 'manager/backers/form' %>
  </div>
</div>

app/views/manager/backers/index.html.erb
<div class="card card-border-color card-border-color-primary">
  <div class="card-body">
    <%= render 'manager/backers/search' %>
  </div> 
  <div class="card-body table-responsive">    
    <% if @backers.present? %>
      <%= render 'manager/backers/list', backers: @backers %>
    <% else %>
      <div class="paxl">
        <h4 class="text-center">Nenhuma doação encontrada!</h4>
      </div>
    <% end %>
  </div>
</div>